version: '3.7'

services:
  ca_org0:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/hl
      - FABRIC_CA_SERVER_CA_NAME=ca-org0
      - FABRIC_CA_SERVER_PORT=7051
      - FABRIC_CA_SERVER_ADDRESS=192.168.21.154
      - FABRIC_CA_SERVER_LISTENADDRESS=192.168.21.154
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./orgs/ca/org0:/hl
    container_name: ca_org0
    network_mode: "host"

  ca_org1:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/hl
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_PORT=7052
      - FABRIC_CA_SERVER_ADDRESS=192.168.21.154
      - FABRIC_CA_SERVER_LISTENADDRESS=192.168.21.154
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17055
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./orgs/ca/org1:/hl
      - ./orgs/common:/hl/common
    container_name: ca_org1
    network_mode: "host"

  ca_org2:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/hl
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_PORT=7053
      - FABRIC_CA_SERVER_ADDRESS=192.168.21.152
      - FABRIC_CA_SERVER_LISTENADDRESS=192.168.21.152
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17056
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./orgs/ca/org2:/hl
      - ./orgs/common:/hl/common
    container_name: ca_org2
    network_mode: "host"

  ca_org3:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/hl
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_ADDRESS=192.168.21.152
      - FABRIC_CA_SERVER_LISTENADDRESS=192.168.21.152
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17057
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./orgs/ca/org3:/hl
      - ./orgs/common:/hl/common
    container_name: ca_org3
    network_mode: "host"

  orderer:
    container_name: orderer
    image: hyperledger/fabric-orderer:2.4.3
    labels:
      service: hyperledger-fabric
    environment:
      - ORDERER_GENERAL_LISTENADDRESS=192.168.21.154
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/hl/msp
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=/hl/genesis.block
    working_dir: /hl
    command: orderer
    volumes:
        - ./orgs/org0/orderer:/hl
    network_mode: "host"

  peer-org1:
    container_name: peer-org1
    image: hyperledger/fabric-peer:2.4.3
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      # Peer specific variables
      - CORE_PEER_ID=peer-org1
      - CORE_PEER_ADDRESS=192.168.21.154:9051
      - CORE_PEER_LISTENADDRESS=192.168.21.154:9051
      - CORE_PEER_CHAINCODEADDRESS=192.168.21.154:9072
      - CORE_PEER_CHAINCODELISTENADDRESS=192.168.21.154:9072
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=192.168.21.154:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=192.168.21.154:9051
      - CORE_OPERATIONS_LISTENADDRESS=192.168.21.154:9444
      - CORE_PEER_LOCALMSPID=UsersMSP
      - CORE_PEER_MSPCONFIGPATH=/hl/peer/msp
    volumes:
        - /var/run:/host/var/run
        - ./orgs/org1:/hl
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    network_mode: "host"

  peer-org2:
    container_name: peer-org2
    image: hyperledger/fabric-peer:2.4.3
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      # Peer specific variables
      - CORE_PEER_ID=peer-org2
      - CORE_PEER_ADDRESS=192.168.21.154:9052
      - CORE_PEER_LISTENADDRESS=192.168.21.152:9052
      - CORE_PEER_CHAINCODEADDRESS=192.168.21.152:9073
      - CORE_PEER_CHAINCODELISTENADDRESS=192.168.21.152:9073
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=192.168.21.152:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=192.168.21.152:9052
      - CORE_OPERATIONS_LISTENADDRESS=192.168.21.152:9445
      - CORE_PEER_LOCALMSPID=ShopsMSP
      - CORE_PEER_MSPCONFIGPATH=/hl/peer/msp
    volumes:
        - /var/run:/host/var/run
        - ./orgs/org2:/hl/
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    network_mode: "host"

  peer-org3:
    container_name: peer-org3
    image: hyperledger/fabric-peer:2.4.3
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      # Peer specific variables
      - CORE_PEER_ID=peer-org3
      - CORE_PEER_ADDRESS=192.168.21.152:9053
      - CORE_PEER_LISTENADDRESS=192.168.21.152:9053
      - CORE_PEER_CHAINCODEADDRESS=192.168.21.152:9074
      - CORE_PEER_CHAINCODELISTENADDRESS=192.168.21.152:9074
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=192.168.21.152:9053
      - CORE_PEER_GOSSIP_BOOTSTRAP=192.168.21.152:9053
      - CORE_OPERATIONS_LISTENADDRESS=192.168.21.152:9446
      - CORE_PEER_LOCALMSPID=BankMSP
      - CORE_PEER_MSPCONFIGPATH=/hl/peer/msp
    volumes:
        - /var/run:/host/var/run
        - ./orgs/org3:/hl
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    network_mode: "host"

  cli-org1:
    container_name: cli-org1
    image: hyperledger/fabric-tools:2.4.3
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_MSPCONFIGPATH=/hl/admin/msp
      - CORE_PEER_ADDRESS=192.168.21.154:9051
      - CORE_PEER_LOCALMSPID=UsersMSP
    working_dir: /common
    command: /bin/bash
    volumes:
        - /var/run:/host/var/run
        - ./orgs/org1:/hl
        - ./orgs/common:/common
    network_mode: "host"

  cli-org2:
    container_name: cli-org2
    image: hyperledger/fabric-tools:2.4.3
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_MSPCONFIGPATH=/hl/admin/msp
      - CORE_PEER_ADDRESS=192.168.21.152:9052
      - CORE_PEER_LOCALMSPID=ShopsMSP
    working_dir: /common
    command: /bin/bash
    volumes:
        - /var/run:/host/var/run
        - ./orgs/org2:/hl
        - ./orgs/common:/common
    network_mode: "host"

  cli-org3:
    container_name: cli-org3
    image: hyperledger/fabric-tools:2.4.3
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_MSPCONFIGPATH=/hl/admin/msp
      - CORE_PEER_ADDRESS=192.168.21.152:9053
      - CORE_PEER_LOCALMSPID=BankMSP
    working_dir: /common
    command: /bin/bash
    volumes:
        - /var/run:/host/var/run
        - ./orgs/org3:/hl
        - ./orgs/common:/common
    network_mode: "host"